CREATE SEQUENCE EXLTMSGHOST.HTHCEV_SEQ_CDG
INCREMENT BY 1
START WITH 1500
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHCIA_SEQ_CDG
INCREMENT BY 1
START WITH 13000
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHCPE_SEQ_CDG
INCREMENT BY 1
START WITH 34000
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHDRC_SEQ_CDG
INCREMENT BY 1
START WITH 212600
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHECA_SEQ_CDG
INCREMENT BY 1
START WITH 12200
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHEVI_SEQ_CDG
INCREMENT BY 1
START WITH 1000
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHEVO_SEQ_CDG
INCREMENT BY 1
START WITH 1000
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHPSE_SEQ_CDG
INCREMENT BY 1
START WITH 18000
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHRTS_SEQ_CDG
INCREMENT BY 1
START WITH 200
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;
CREATE SEQUENCE EXLTMSGHOST.HTHTPT_SEQ_CDG
INCREMENT BY 1
START WITH 110
NOMAXVALUE
MINVALUE 1
CACHE 20 NOCYCLE
NOORDER
;


 
-- SINONIMOS DE SECUENCIAS.
CREATE PUBLIC SYNONYM HTHCEV_SEQ_CDG FOR EXLTMSGHOST.HTHCEV_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHCIA_SEQ_CDG FOR EXLTMSGHOST.HTHCIA_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHCPE_SEQ_CDG FOR EXLTMSGHOST.HTHCPE_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHDRC_SEQ_CDG FOR EXLTMSGHOST.HTHDRC_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHECA_SEQ_CDG FOR EXLTMSGHOST.HTHECA_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHEVI_SEQ_CDG FOR EXLTMSGHOST.HTHEVI_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHEVO_SEQ_CDG FOR EXLTMSGHOST.HTHEVO_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHPSE_SEQ_CDG FOR EXLTMSGHOST.HTHPSE_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHRTS_SEQ_CDG FOR EXLTMSGHOST.HTHRTS_SEQ_CDG;
CREATE PUBLIC SYNONYM HTHTPT_SEQ_CDG FOR EXLTMSGHOST.HTHTPT_SEQ_CDG;



-- Grant a secuencias
GRANT SELECT ON EXLTMSGHOST.HTHCEV_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHCIA_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHCPE_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHECA_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHDRC_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHEVI_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHEVO_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHPSE_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHRTS_SEQ_CDG TO SRVLTMSGHOST;
GRANT SELECT ON EXLTMSGHOST.HTHTPT_SEQ_CDG TO SRVLTMSGHOST;


GRANT SELECT, INSERT, UPDATE, DELETE ON EXCECOP.DIFE_HORARIA TO SRVLTMSGHOST;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXPRICING.DOMINIOS TO SRVLTMSGHOST;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXPRICING.CODIGO_DOMINIOS TO SRVLTMSGHOST;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXGEOGRA.CIUDADES TO SRVLTMSGHOST;
GRANT SELECT, INSERT, UPDATE, DELETE ON ARUSER.CLIENTES TO SRVLTMSGHOST;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXBITACO.LINEAS_AEREAS TO SRVLTMSGHOST;
 
 
COMMIT;