--------------------------------------------------------
-- Archivo creado  - jueves-julio-28-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HTH_FILE
--------------------------------------------------------

  CREATE TABLE "EXLTMGHOSTFT"."HTH_FILE" 
   (	"FILENAME" VARCHAR2(255 BYTE), 
	"START_TEST_DATETIME" DATE, 
	"FINISH_TEST_DATETIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HTH_TESTCASE
--------------------------------------------------------

  CREATE TABLE "EXLTMGHOSTFT"."HTH_TESTCASE" 
   (	"RESULT" NUMBER(1,0), 
	"FILENAME" VARCHAR2(255 BYTE), 
	"START_TEST_DATETIME" DATE, 
	"TESTCASE_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HTH_VALIDATION
--------------------------------------------------------

  CREATE TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" 
   (	"START_TEST_DATETIME" DATE, 
	"FILENAME" VARCHAR2(255 BYTE), 
	"RESULT" NUMBER(1,0), 
	"EXPECTED" CLOB, 
	"REAL" CLOB, 
	"TECHNICAL" CLOB, 
	"TESTCASE_NAME" VARCHAR2(255 BYTE), 
	"VALIDATION_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("EXPECTED") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("REAL") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TECHNICAL") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index TESTCASE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EXLTMGHOSTFT"."TESTCASE_PK" ON "EXLTMGHOSTFT"."HTH_TESTCASE" ("START_TEST_DATETIME", "FILENAME", "TESTCASE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HTH_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EXLTMGHOSTFT"."HTH_FILE_PK" ON "EXLTMGHOSTFT"."HTH_FILE" ("FILENAME", "START_TEST_DATETIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BIN$Ia7BOGOs1KrgUAoKvO5Xzg==$0
--------------------------------------------------------

  CREATE UNIQUE INDEX "EXLTMGHOSTFT"."BIN$Ia7BOGOs1KrgUAoKvO5Xzg==$0" ON "EXLTMGHOSTFT"."HTH_VALIDATION" ("FILENAME", "START_TEST_DATETIME", "TESTCASE_NAME", "VALIDATION_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HTH_TESTCASE
--------------------------------------------------------

  ALTER TABLE "EXLTMGHOSTFT"."HTH_TESTCASE" MODIFY ("RESULT" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_TESTCASE" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_TESTCASE" MODIFY ("START_TEST_DATETIME" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_TESTCASE" MODIFY ("TESTCASE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_TESTCASE" ADD CONSTRAINT "TESTCASE_PK" PRIMARY KEY ("START_TEST_DATETIME", "FILENAME", "TESTCASE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HTH_VALIDATION
--------------------------------------------------------

  ALTER TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" MODIFY ("START_TEST_DATETIME" CONSTRAINT "BIN$Ia7BOGOm1KrgUAoKvO5Xzg==$0" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" MODIFY ("FILENAME" CONSTRAINT "BIN$Ia7BOGOn1KrgUAoKvO5Xzg==$0" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" MODIFY ("RESULT" CONSTRAINT "BIN$Ia7BOGOo1KrgUAoKvO5Xzg==$0" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" ADD CONSTRAINT "BIN$Ia7BOGOp1KrgUAoKvO5Xzg==$0" PRIMARY KEY ("FILENAME", "START_TEST_DATETIME", "TESTCASE_NAME", "VALIDATION_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" MODIFY ("TESTCASE_NAME" CONSTRAINT "BIN$Ia7BOGOq1KrgUAoKvO5Xzg==$0" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" MODIFY ("VALIDATION_NAME" CONSTRAINT "BIN$Ia7BOGOr1KrgUAoKvO5Xzg==$0" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HTH_FILE
--------------------------------------------------------

  ALTER TABLE "EXLTMGHOSTFT"."HTH_FILE" ADD CONSTRAINT "HTH_FILE_PK" PRIMARY KEY ("FILENAME", "START_TEST_DATETIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_FILE" MODIFY ("FILENAME" NOT NULL ENABLE);
 
  ALTER TABLE "EXLTMGHOSTFT"."HTH_FILE" MODIFY ("START_TEST_DATETIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HTH_TESTCASE
--------------------------------------------------------

  ALTER TABLE "EXLTMGHOSTFT"."HTH_TESTCASE" ADD CONSTRAINT "HTH_TESTCASE_FK1" FOREIGN KEY ("FILENAME", "START_TEST_DATETIME")
	  REFERENCES "EXLTMGHOSTFT"."HTH_FILE" ("FILENAME", "START_TEST_DATETIME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HTH_VALIDATION
--------------------------------------------------------

  ALTER TABLE "EXLTMGHOSTFT"."HTH_VALIDATION" ADD CONSTRAINT "HTH_VALIDATION_FK1" FOREIGN KEY ("START_TEST_DATETIME", "FILENAME", "TESTCASE_NAME")
	  REFERENCES "EXLTMGHOSTFT"."HTH_TESTCASE" ("START_TEST_DATETIME", "FILENAME", "TESTCASE_NAME") ENABLE;
	  
COMMIT;
EXIT;
