--create DFHR table
CREATE TABLE EXCECOP.DIFE_HORARIA 
(
  SID_HOST NUMBER(2, 0) NOT NULL 
, SID_SEQ NUMBER NOT NULL 
, SID_DATE DATE 
, PSTS_CDG VARCHAR2(3 BYTE) NOT NULL 
, DFHR_FCH_DESDE DATE NOT NULL 
, DFHR_FCH_HASTA DATE NOT NULL 
, DFHR_VLR NUMBER(2, 0) 
, CONSTRAINT DFHR_PK PRIMARY KEY 
  (
    PSTS_CDG 
  , DFHR_FCH_DESDE 
  , DFHR_FCH_HASTA 
  )
  ENABLE 
);
CREATE PUBLIC SYNONYM DFHR FOR EXCECOP.DIFE_HORARIA;

--create DMNO table
CREATE TABLE EXPRICING.DOMINIOS 
(
  DMNO_ID VARCHAR2(30 BYTE) NOT NULL 
, DMNO_DSC VARCHAR2(50 BYTE) NOT NULL 
, DMNO_ATTR_1 VARCHAR2(30 BYTE) 
, DMNO_ATTR_2 VARCHAR2(30 BYTE) 
, DMNO_ATTR_3 VARCHAR2(30 BYTE) 
, DMNO_ATTR_4 VARCHAR2(30 BYTE) 
, DMNO_ATTR_5 VARCHAR2(30 BYTE) 
, DMNO_ATTR_6 VARCHAR2(30 BYTE) 
, DMNO_ATTR_7 VARCHAR2(30 BYTE) 
, DMNO_ATTR_8 VARCHAR2(30 BYTE) 
, DMNO_ATTR_9 VARCHAR2(30 BYTE) 
, DMNO_ATTR_10 VARCHAR2(30 BYTE) 
, CONSTRAINT DMNO_PK PRIMARY KEY 
  (
    DMNO_ID 
  )
  ENABLE 
);
CREATE PUBLIC SYNONYM DMNO FOR EXPRICING.DOMINIOS;

--create CDDN table
CREATE TABLE EXPRICING.CODIGO_DOMINIOS 
(
  DMNO_ID VARCHAR2(30 BYTE) NOT NULL 
, CDDN_ID VARCHAR2(30 BYTE) NOT NULL 
, CDDN_VLR_ATTR_1 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_2 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_3 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_4 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_5 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_6 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_7 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_8 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_9 VARCHAR2(30 BYTE)
, CDDN_VLR_ATTR_10 VARCHAR2(30 BYTE)
, CONSTRAINT CDDN_PK PRIMARY KEY 
  (
    DMNO_ID
  , CDDN_ID
  )
  ENABLE 
);
CREATE PUBLIC SYNONYM CDDN FOR EXPRICING.CODIGO_DOMINIOS;
ALTER TABLE EXPRICING.CODIGO_DOMINIOS
ADD CONSTRAINT CDDN_FK_DMNO_1 FOREIGN KEY
(
  DMNO_ID 
)
REFERENCES EXPRICING.DOMINIOS
(
  DMNO_ID 
);

--create CDDS table
CREATE TABLE EXGEOGRA.CIUDADES 
(
  SID_HOST NUMBER(2, 0) NOT NULL 
, SID_SEQ NUMBER NOT NULL 
, SID_DATE DATE 
, CDDS_CDG_IATA VARCHAR2(3 BYTE) NOT NULL 
, CDDS_CDG_AREA_IATA NUMBER(1, 0) NOT NULL 
, CDDS_GLS VARCHAR2(30 BYTE) NOT NULL 
, CDDS_TLF_CDG_AREA NUMBER(5, 0) 
, PSES_CDG_ISO VARCHAR2(2 BYTE) NOT NULL 
, ESTD_CDG_IATA VARCHAR2(2 BYTE) 
, CDDS_LAT_CARD VARCHAR2(3 BYTE) 
, CDDS_LAT_GRAD NUMBER(3, 0) 
, CDDS_LAT_MINU NUMBER(2, 0) 
, CDDS_LAT_SEGU NUMBER(2, 0) 
, CDDS_LONG_CARD VARCHAR2(3 BYTE) 
, CDDS_LONG_GRAD NUMBER(3, 0) 
, CDDS_LONG_MINU NUMBER(2, 0) 
, CDDS_LONG_SEGU NUMBER(2, 0) 
, CDDS_ALTITUD NUMBER(5, 2) 
, ZNHR_CDG VARCHAR2(5 BYTE) 
, CONSTRAINT CDDS_PK PRIMARY KEY 
  (
    CDDS_CDG_IATA 
  )
  ENABLE 
);
CREATE PUBLIC SYNONYM CDDS FOR EXGEOGRA.CIUDADES;

--create CLIE table
CREATE TABLE ARUSER.CLIENTES 
(
  SID_HOST NUMBER(2, 0) NOT NULL 
, SID_SEQ NUMBER NOT NULL 
, SID_DATE DATE 
, N_CLIENTE NUMBER(6, 0) NOT NULL 
, C_POSTA_CLIE VARCHAR2(3 BYTE) NOT NULL 
, NOM_RSOCIAL VARCHAR2(40 BYTE) 
, CALLE_PPAL VARCHAR2(40 BYTE) 
, CIUDAD_PPAL VARCHAR2(20 BYTE) 
, C_PAIS_PPAL VARCHAR2(2 BYTE) 
, C_STATE_PPAL VARCHAR2(2 BYTE) 
, C_ZIP_PPAL VARCHAR2(5 BYTE) 
, CALLE_POST VARCHAR2(40 BYTE) 
, CIUDAD_POST VARCHAR2(20 BYTE) 
, C_PAIS_POST VARCHAR2(2 BYTE) 
, C_STATE_POST VARCHAR2(2 BYTE) 
, C_ZIP_POST VARCHAR2(5 BYTE) 
, N_FONO_1 VARCHAR2(15 BYTE) 
, N_FONO_2 VARCHAR2(15 BYTE) 
, N_FAX VARCHAR2(15 BYTE) 
, N_RUT VARCHAR2(15 BYTE) 
, C_AREA_CIUDA VARCHAR2(5 BYTE) 
, C_POSTA VARCHAR2(3 BYTE) 
, F_CREACION DATE 
, C_IATA NUMBER 
, T_CREDITO NUMBER(14, 2) 
, E_MAIL VARCHAR2(50 BYTE) 
, CONSTRAINT PK_CLIE_00_8K PRIMARY KEY 
  (
    N_CLIENTE 
  , C_POSTA_CLIE 
  )
  ENABLE 
);
CREATE PUBLIC SYNONYM CLIE FOR ARUSER.CLIENTES;

--create LNAR table
CREATE TABLE EXBITACO.LINEAS_AEREAS 
(
  LNAR_CDG_IATA VARCHAR2(3 BYTE) NOT NULL 
, LNAR_CLASIFICACION VARCHAR2(1 BYTE) 
, LNAR_NMR_IATA VARCHAR2(4 BYTE) 
, CLNT_CDG NUMBER(9, 0) 
, LNAR_DSC VARCHAR2(30 BYTE) 
, PSES_CDG_ISO VARCHAR2(2 BYTE) 
, LNAR_ZONA VARCHAR2(1 BYTE) 
, LNAR_FLAG_CH VARCHAR2(1 BYTE) 
, COM_STD_VOL NUMBER(13, 0) 
, SID_HOST NUMBER(2, 0) 
, SID_SEQ NUMBER 
, SID_DATE DATE 
, LNAR_ISC NUMBER(5, 2) 
, LNAR_FCH_CAMBIO_CH DATE 
, LNAR_FLAG_IDEC VARCHAR2(1 BYTE) 
, LNAR_CDG_IATA_REAL VARCHAR2(3 BYTE) 
, LNAR_CDG_MATRIX VARCHAR2(3 BYTE) 
, N_CLIENTE NUMBER(6, 0) 
, C_POSTA_CLIE VARCHAR2(3 BYTE) 
, CONSTRAINT LNAR_PK PRIMARY KEY 
  (
    LNAR_CDG_IATA 
  )
  ENABLE 
);
CREATE PUBLIC SYNONYM LNAR FOR EXBITACO.LINEAS_AEREAS;

COMMIT;
EXIT;
-- EOF